# Uncomment the next line to define a global platform for your project
# platform :ios, ’16.0’

target 'Remini' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Remini

  target 'ReminiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReminiUITests' do
    # Pods for testing
  end
pod 'BottomSheetSwiftUI', '~> 3.1.1'
pod 'Kingfisher', '~> 7.0'
pod 'SQLite.swift', '~> 0.14.0'
pod 'OpenMinedSwiftSyft', '~> 0.1.3-beta1'
end
